### ISSUE TITLE
Pure functions for better tree shaking

### ISSUE THREAD

**Issue by kripod** [omgovich/colord#16]
I think a functional API only with pure functions should be available from a separate package entry point, e.g. `colord/pure` or `colord/fp`. That approach would also offer seamless extensibility without having to think about the bundling and application of plugins.

I also think that a functional API could complement the currently available chained methods, and the latter could rely upon calling the exported pure functions.

**Comment by omgovich** [comment]
I did research before starting the development and decided to go with chainable API since developers choose libraries with a good and easy API. If you check NPM you'll see that there are no popular libraries with a functional approach.

So I decided to create a tiny chainable core and a plugin system around so the library so it kinda mimics tree-shakeable approach.

Providing pure functions is not a way I would like to go since people actually don't want that.

There are pure-function-based libraries already like [`color-fns`](https://www.npmjs.com/package/@swiftcarrot/color-fns) but, I guess, a difficult API stops people from using it.

Combining the chainable and FP in one package is super tricky, so I'm not sure I want to invest in that.
The **Colord**'s way is providing the familiar API while caring about a target bundle package.
