### ISSUE TITLE
Add hue manipulation

### ISSUE THREAD

**Issue by GMartigny** [omgovich/colord#48]
The library support saturation and lightness manipulation but not hue. This was quite surprising for me.

I can propose a PR if you're ok with it.

**Comment by omgovich** [comment]
Hey 👋 Could you please provide some examples of the API you need?
As far as I understand you suggested to add something like `colord('#abc').spin(-90)`, right?

**Comment by GMartigny** [comment]
"Need" is a strong word, but yeah `colord("#123").spin()`, `colord("#123").rotate()` or `colord("#123").hue()` could be a logical addition to the API (IMO).

**Comment by omgovich** [comment]
Thanks for your advice, I'll definitely think about that ❤️
I try to keep the core as light as possible and avoid extra methods, but having one or two hue manipulation methods seems logical, totally agree!

**Comment by paarthenon** [comment]
I'd like to second this request. I started using this library today and was surprised when hue manipulation didn't exist. It felt a bit more unexpected because **s**aturation and **l**ight value adjustment both do. 

I ended up translating to hsl and manipulating the values in that model. This was no big deal, but a built in feature would have been nice to avoid the hiccup.

I'm also open to contributing it if you have the desire but not the time.

**Comment by omgovich** [comment]
Hey guys! I just came back from my honeymoon. Going to add the hue manipulation methods later this week.

**Comment by omgovich** [comment]
Hey guys! Check v2.1 with the new `hue` and `rotate` methods included.

**Comment by paarthenon** [comment]
Seems to work well, thank you for being open to the change!
